name = "inconigto-mode"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = true

domains = [
  "inconigto.web.id",
  "inconigto.biz.id",
  "inconigtovpn.web.id",
  "inconigtovpn.biz.id"
]

routes = [
  for domain in domains {
    { pattern = domain, custom_domain = true },
    { pattern = "ava.game.naver.com.${domain}", custom_domain = true },
    { pattern = "df.game.naver.com.${domain}", custom_domain = true },
    { pattern = "graph.instagram.com.${domain}", custom_domain = true },
    { pattern = "zaintest.vuclip.com.${domain}", custom_domain = true },
    { pattern = "support.zoom.us.${domain}", custom_domain = true },
    { pattern = "cache.netflix.com.${domain}", custom_domain = true },
    { pattern = "quiz.int.vidio.com.${domain}", custom_domain = true }  # Fixed the extra 'c'
  }
]

[vars]
