name: Update Domains and Routes in wrangler.toml

on:
  push:
    paths:
      - domains.json  # This will trigger the action when domains.json changes

jobs:
  update-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install Dependencies
        run: |
          npm install  # This will install dependencies if there are any

      - name: Update wrangler.toml with new domains
        run: |
          DOMAIN_JSON_FILE="domains.json"
          WRANGLER_FILE="wrangler.toml"

          # Read the domains from the JSON file
          DOMAINS=$(jq -r '.domains' $DOMAIN_JSON_FILE)

          # Loop through domains and create the routes for them
          for domain in $(echo "$DOMAINS" | jq -r '.[]'); do
            # Check if routes already exist
            ROUTES=$(grep -oP "(?<=\{ pattern = \").*${domain}(?=\")" $WRANGLER_FILE)

            # If routes don't exist, add them
            if [ -z "$ROUTES" ]; then
              # Add routes for the domain
              NEW_ROUTES="{ pattern = \"${domain}\", custom_domain = true },"
              NEW_ROUTES+="\n{ pattern = \"ava.game.naver.com.${domain}\", custom_domain = true },"
              NEW_ROUTES+="\n{ pattern = \"df.game.naver.com.${domain}\", custom_domain = true },"
              NEW_ROUTES+="\n{ pattern = \"graph.instagram.com.${domain}\", custom_domain = true },"
              NEW_ROUTES+="\n{ pattern = \"zaintest.vuclip.com.${domain}\", custom_domain = true },"
              NEW_ROUTES+="\n{ pattern = \"support.zoom.us.${domain}\", custom_domain = true },"
              NEW_ROUTES+="\n{ pattern = \"cache.netflix.com.${domain}\", custom_domain = true }"

              # Append the new routes to wrangler.toml
              echo -e "$NEW_ROUTES" >> $WRANGLER_FILE
            fi
          done

      - name: Commit updated wrangler.toml
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add wrangler.toml
          git commit -m "Update wrangler.toml with new domains and routes"
          git push
